In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,mean_squared_error,root_mean_squared_error,confusion_matrix
import pickle as pk

In [2]:
df= pd.read_csv("loan_approval_dataset.csv")

In [3]:
df.isna().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

In [4]:
df

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [5]:
df.keys()

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df.keys()

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'cibil_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='object')

In [8]:
df['education'].unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [9]:
df['education'] = df['education'].apply(lambda x : x.strip())

In [10]:
df['education'] = df['education'].replace("Graduate","1").replace("Not Graduate","0").astype(int)

In [11]:
df['education'].unique()

array([1, 0])

In [12]:
df['self_employed'].unique()

array([' No', ' Yes'], dtype=object)

In [13]:
df['self_employed'] = df['self_employed'].apply(lambda x : x.strip())

In [14]:
df['self_employed'] = df['self_employed'].replace("Yes","1").replace("No","0").astype(int)

In [15]:
df['self_employed'].unique()

array([0, 1])

In [16]:
df['loan_status'].unique()

array([' Approved', ' Rejected'], dtype=object)

In [17]:
df['loan_status'] = df['loan_status'].apply(lambda x :x.strip())

In [18]:
df['loan_status'] = df['loan_status'].replace("Approved","1").replace("Rejected","0").astype(int)

In [19]:
df['loan_status'].unique()

array([1, 0])

In [20]:
df['Assets'] = df['residential_assets_value'] + df['commercial_assets_value'] + df['luxury_assets_value'] + df['bank_asset_value']

In [21]:
df.drop(columns=['loan_id','residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'],inplace=True)

In [22]:
df

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,1,50700000
1,0,0,1,4100000,12200000,8,417,0,17000000
2,3,1,0,9100000,29700000,20,506,0,57700000
3,3,1,0,8200000,30700000,8,467,0,52700000
4,5,0,1,9800000,24200000,20,382,0,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,0,7400000
4265,0,0,1,3300000,11300000,20,559,1,20000000
4266,2,0,0,6500000,23900000,18,457,0,39000000
4267,1,0,0,4100000,12800000,8,780,1,28800000
4268,1,1,0,9200000,29700000,10,607,1,77300000

In [23]:
x = df.drop(columns="loan_status")
y = df["loan_status"]

In [24]:
x.keys()

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'Assets'],
      dtype='object')

In [25]:
# plt.figure(figsize=(10,8))
# sns.heatmap(x.corr(),annot=True)

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=23)

In [27]:
scaler = StandardScaler()
scaled_x_train = scaler.fit_transform(x_train)
scaled_x_test = scaler.transform(x_test)

# Logistic Regression

In [28]:
model1  = LogisticRegression()

In [29]:
model1.fit(scaled_x_train,y_train)

LogisticRegression()

In [30]:
y_pred1 = model1.predict(scaled_x_test)

In [31]:
accuracyscore = accuracy_score(y_test,y_pred1)
mse = mean_squared_error(y_test,y_pred1)
rms = np.sqrt(mse)

In [32]:
print("Accuracy_socre",accuracyscore)
print("Mean_squared,error",mse)
print("Mean_squared,error",rms)

Accuracy_socre 0.9180327868852459
Mean_squared,error 0.08196721311475409
Mean_squared,error 0.2862991671569341

In [33]:
# sns.heatmap(confusion_matrix(y_test,y_pred1),annot=True)

# Decision Tree

In [34]:
model2  = DecisionTreeClassifier(criterion="entropy")

In [35]:
model2.fit(scaled_x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [36]:
y_pred2 = model2.predict(scaled_x_test)

In [37]:
accuracyscore = accuracy_score(y_test,y_pred2)
mse = mean_squared_error(y_test,y_pred2)
rms = np.sqrt(mse)

In [38]:
print("Accuracy_socre",accuracyscore)
print("Mean_squared,error",mse)
print("Mean_squared,error",rms)

Accuracy_socre 0.9836065573770492
Mean_squared,error 0.01639344262295082
Mean_squared,error 0.12803687993289598

In [39]:
# sns.heatmap(confusion_matrix(y_test,y_pred2),annot=True)

# Random Forest

In [40]:
model3 = RandomForestClassifier(n_estimators=100)

In [41]:
model3.fit(scaled_x_train,y_train)

RandomForestClassifier()

In [42]:
y_pred3 = model3.predict(scaled_x_test)

In [43]:
accuracyscore = accuracy_score(y_test,y_pred3)
mse = mean_squared_error(y_test,y_pred3)
rms = np.sqrt(mse)

In [44]:
print("Accuracy_socre",accuracyscore)
print("Mean_squared,error",mse)
print("Mean_squared,error",rms)

Accuracy_socre 0.9800936768149883
Mean_squared,error 0.01990632318501171
Mean_squared,error 0.14108976995165776

In [45]:
# sns.heatmap(confusion_matrix(y_test,y_pred2),annot=True)

In [46]:
pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents', 'education', 'self_employed', 'income_annum','loan_amount', 'loan_term', 'cibil_score', 'Assets'])

In [47]:
pred_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,Assets
0,2,1,0,9600000,29900000,12,778,50700000

In [49]:
scaler.transform(pred_data)

array([[-0.29434668,  0.98690853, -1.00322629,  1.62161264,  1.62627708,
         0.19538724,  1.02917992,  0.93622493]])

In [50]:
#using logistic regression makea prediction
model1.predict(pred_data)

c:\Users\INDIA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

array([1])

In [51]:
pk.dump(model1,open('logisticreg.pkl','wb'))

In [52]:
pk.dump(model2,open('decisiontree.pkl','wb'))

In [53]:
pk.dump(model3,open('randomforest.pkl','wb'))

In [54]:
pk.dump(scaler,open("scaler.pkl",'wb'))